name: Java CI with Maven
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 21 ]
    name: Java ${{ matrix.java }} build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'liberica'
        cache: 'maven'

    - name: Adjust memory use for Maven
      run: echo "MAVEN_OPTS='-Xmx2g'" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B verify --no-transfer-progress